services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: planillas-api
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_gjhU4ALcJT8O@ep-curly-brook-adbnqkk1-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
      - CORS_ORIGINS=http://localhost,http://localhost:5173,http://localhost:80
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: planillas-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
